---
- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis is installed.
  package:
    name: "{{ redis_package }}"
    state: present

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
    owner: root
    group: redis
  notify: restart redis

- name: execute installation of data folder as recommended by SuSE
  ansible.builtin.command: "install -d -o redis -g redis -m 0750 /var/lib/redis/{{ redis_instancename }}/"

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
