---
# Get distribution specific vars:
- name: include distribution specific vars
  include_vars: "{{ansible_distribution}}_{{ansible_distribution_version}}.yml"

- name: Ensure coreutils are present
  ansible.builtin.package:
    name: "coreutils"
    state: present

- name: Ensure Redis is installed.
  ansible.builtin.package:
    name: "{{ redis_package }}"
    state: present

- name: Ensure Redis configuration dir exists.
  ansible.builtin.file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  ansible.builtin.template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
    owner: root
    group: redis
  notify: restart redis

- name: execute installation of data folder as recommended by SuSE
  ansible.builtin.command:
    argv:
      - /usr/bin/install
      - -d
      - -o
      - redis
      - -g
      - redis
      - -m
      - 0750
      - "/var/lib/redis/{{ redis_instancename }}/"
#  args:
#    cmd: >
#      "/usr/bin/install -d -o redis -g redis -m 0750
#      /var/lib/redis/{{ redis_instancename }}/"

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
