---
- name: Converge
  hosts: all
  tasks:
    - name: "Include geekoops-redis"
      include_role:
        name: "geekoops-redis"
    ## Setup test enviroment
    # test whether redis server accepts connections on the unix socket
    - name: test connection to socket
      ansible.builtin.command:
        argv:
          - redis-benchmark
          - -q
          - -n
          - 100
          - -s
          - /var/run/redis/{{ redis_instancename }}.sock
