---
- name: Converge
  hosts: all
  tasks:
    - name: "Include geekoops-redis"
      include_role:
        name: "geekoops-redis"
    ## Setup test enviroment
    # test whether redis server accepts connections on the unix socket
    - name: test connection to socket
      tags: molecule-idempotence-notest
      ansible.builtin.command:
        argv:
          - redis-cli
          - -s
          - /var/run/redis/default.sock
          - ping
