FROM registry.opensuse.org/opensuse/leap:16.0

# Install systemd and development tools, clear cache
RUN zypper in -y systemd systemd-sysvinit firewalld python3 python3-firewall curl coreutils && rm -rf /var/cache/*

# Start container with systemd
ENTRYPOINT ["/usr/sbin/init"]
